version: '3'

services:
    mta:
        image: boky/postfix
        ports: 
            - "587:587"
        environment:
            ALLOWED_SENDER_DOMAINS: "example.com"
     
    monitoring:
        image: prom/prometheus
        ports: 
            - "9090:9090"
        volumes: 
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
    app:
        build:
            context: .
        ports: 
            - "8080:8080"
        env_file:
            - ".env"
        volumes: 
            - ./data:/data

    app_production:
        image: kisteio/mail-fanout:latest
        ports: 
            - "8080:8080"
        env_file:
            - ".env.production"
        volumes: 
            - ./data:/data
    
    mongodb:
        image: mongo:4.4.8
        container_name: senkenberg_mongo
        restart: always
        networks:
          - conformation_storage
        env_file:
          - .env
        ports:
          - 27021:27017
        volumes:
          - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
          - ./data:/data/db
        command: --auth --wiredTigerCacheSizeGB 0.5

            

networks:
  storage:
    external:
      name: conformation_storage