version: '3'

services:
    mta:
        image: boky/postfix
        environment:
            ALLOWED_SENDER_DOMAINS: "example.com"
     
    monitoring:
        image: prom/prometheus
        ports: 
            - "9090:9090"
        volumes: 
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
    app:
        build:
            context: .
        ports: 
            - "8080:8080"
        env_file:
            - ".env.production"
        volumes: 
            - ./data:/data

        

            

