require('dotenv').config()


const MAILBOX_HOST = process.env.MAILBOX_HOST || '';
const MAILBOX_PORT = Math.floor(process.env.MAILBOX_PORT) || 25;


const SEND_PREDEFINED_EMAIL_TARGET_FROM = process.env.SEND_PREDEFINED_EMAIL_TARGET_FROM || '';
const SEND_PREDEFINED_EMAIL_TARGET_TO = process.env.SEND_PREDEFINED_EMAIL_TARGET_TO || '';
const SEND_PREDEFINED_EMAIL_TARGET_SUBJECT = process.env.SEND_PREDEFINED_EMAIL_TARGET_SUBJECT || '';

const SEND_OBTAINED_EMAIL_TARGET_FROM = process.env.SEND_OBTAINED_EMAIL_TARGET_FROM || '';
const SEND_OBTAINED_EMAIL_TARGET_SUBJECT = process.env.SEND_OBTAINED_EMAIL_TARGET_SUBJECT || '';


const PAYLOAD_SCHEMAS_DIR_PATH = process.env.PAYLOAD_SCHEMAS_DIR_PATH || './schemas'

module.exports = {
    MAILBOX_HOST,
    MAILBOX_PORT,
    
    SEND_PREDEFINED_EMAIL_TARGET_FROM,
    SEND_PREDEFINED_EMAIL_TARGET_TO,
    SEND_PREDEFINED_EMAIL_TARGET_SUBJECT,
    
    SEND_OBTAINED_EMAIL_TARGET_FROM,
    SEND_OBTAINED_EMAIL_TARGET_SUBJECT,

    PAYLOAD_SCHEMAS_DIR_PATH
    
}