name: Build and publish mail-fanout app

on:
  push:
    paths:
      - "examples/mail-fanout/**"

defaults:
  run:
    working-directory: examples/mail-fanout


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: kisteio
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
     
      - name: Build image
        run: |
          ls -la
          docker build . --file Dockerfile --tag kisteio/mail-fanout

      - name: Push image
        run: |          
          docker push kisteio/mail-fanout