name: Build and publish confirmation app

on:
  push:
    paths:
      - "apps/confirmation/**"

defaults:
  run:
    working-directory: apps/confirmation


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: kisteio
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
     
      - name: Build image
        run: |
          ls -la
          docker build . --file Dockerfile --tag kisteio/confirmation

      - name: Push image
        run: |          
          docker push kisteio/confirmation