name: Build and publish mail-fanout app

on:
  push:
    paths:
      - "examples/mail-fanout/**"

defaults:
  run:
    shell: bash
    working-directory: examples/mail-fanout


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: kisteio
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: examples/mail-fanout
          tags: kisteio/mail-fanout:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}