name: Build and publish mail-fanout app

on:
  push:
    paths:
      - "examples/mail-fanout/**"

defaults:
  run:
    shell: bash
    working-directory: examples/mail-fanout


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: kisteio
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
     
      - name: Build image
        run: |
          ls -la
          docker build . --file Dockerfile --tag kisteio/mail-fanout

      - name: Push image
        run: |
          IMAGE_ID=kisteio/mail-fanout

          VERSION=$(cat service1/VERSION)

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION